[build]
  command = "npm run build"
  publish = "dist"

[template.environment]
  VUE_APP_API_KEY = "AIzaSyCvPHlOe5PH6hctUWRPdIsCVSdHzHBtwi4"
  VUE_APP_FIREBASE_API_KEY = "AIzaSyAsSnm1JakvdKtA1mpta54_7_dzuev1bpo"
  VUE_APP_FIREBASE_AUTH_DOMAIN = "geoguess-1b68e.firebaseapp.com"
  VUE_APP_FIREBASE_DATABASE_URL = "https://geoguess-1b68e-default-rtdb.firebaseio.com"
  VUE_APP_FIREBASE_PROJECT_ID = "geoguess-1b68e"
  VUE_APP_STORAGE_BUCKET = "geoguess-1b68e.appspot.com"
  VUE_APP_FIREBASE_MESSAGING_SENDER_ID = "165746106949"
  VUE_APP_FIREBASE_APP_ID = "1:165746106949:web:d5ccc7dc45cfe65f76392c"
  VUE_APP_FIREBASE_MEASUREMENT_ID = "G-SEDWMKLJ18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
